// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbhZZutYj6zdNN5G6Cb0axDO2lgokmAv8',
    appId: '1:570232335671:web:ececb8c83493ac5b893eb2',
    messagingSenderId: '570232335671',
    projectId: 'irfpe-system',
    authDomain: 'irfpe-system.firebaseapp.com',
    storageBucket: 'irfpe-system.firebasestorage.app',
    measurementId: 'G-1BD4SCRR4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvemScUo-DuYFfPS3nGO-3e_Oa8IW8d0Y',
    appId: '1:570232335671:android:35bd6b0a2ad54db4893eb2',
    messagingSenderId: '570232335671',
    projectId: 'irfpe-system',
    storageBucket: 'irfpe-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIs4etGb-R0jyjCQPZ5UxwviNYeiLyCQ',
    appId: '1:570232335671:ios:dc4a8442f2e01367893eb2',
    messagingSenderId: '570232335671',
    projectId: 'irfpe-system',
    storageBucket: 'irfpe-system.firebasestorage.app',
    iosBundleId: 'com.example.robolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIs4etGb-R0jyjCQPZ5UxwviNYeiLyCQ',
    appId: '1:570232335671:ios:dc4a8442f2e01367893eb2',
    messagingSenderId: '570232335671',
    projectId: 'irfpe-system',
    storageBucket: 'irfpe-system.firebasestorage.app',
    iosBundleId: 'com.example.robolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbhZZutYj6zdNN5G6Cb0axDO2lgokmAv8',
    appId: '1:570232335671:web:51ad16c070d555aa893eb2',
    messagingSenderId: '570232335671',
    projectId: 'irfpe-system',
    authDomain: 'irfpe-system.firebaseapp.com',
    storageBucket: 'irfpe-system.firebasestorage.app',
    measurementId: 'G-NTCC1WNHGR',
  );
}
